CREATE USER nv001 IDENTIFIED BY 001
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv001;

CREATE USER nv002 IDENTIFIED BY 002
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv002;

CREATE USER nv003 IDENTIFIED BY 003
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv003;

CREATE USER nv004 IDENTIFIED BY 004
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv004;

CREATE USER nv005 IDENTIFIED BY 005
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv005;

CREATE USER nv006 IDENTIFIED BY 006
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv006;

CREATE USER nv007 IDENTIFIED BY 007
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv007;

CREATE USER nv008 IDENTIFIED BY 008
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv008;

CREATE USER nv009 IDENTIFIED BY 009
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv009;

CREATE USER nv010 IDENTIFIED BY 010
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv010;

CREATE USER nv011 IDENTIFIED BY 011
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv011;

CREATE USER nv012 IDENTIFIED BY 012
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv012;

CREATE USER nv013 IDENTIFIED BY 013
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv013;

CREATE USER nv014 IDENTIFIED BY 014
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv014;

CREATE USER nv015 IDENTIFIED BY 015
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv015;

CREATE USER nv016 IDENTIFIED BY 016
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv016;

CREATE USER nv017 IDENTIFIED BY 017
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv017;

CREATE USER nv018 IDENTIFIED BY 018
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv018;

CREATE USER nv019 IDENTIFIED BY 019
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv019;

CREATE USER nv020 IDENTIFIED BY 020
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv020;

CREATE USER nv021 IDENTIFIED BY 021
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv021;

CREATE USER nv022 IDENTIFIED BY 022
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv022;

CREATE USER nv023 IDENTIFIED BY 023
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv023;

CREATE USER nv024 IDENTIFIED BY 024
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv024;

CREATE USER nv025 IDENTIFIED BY 025
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION to nv025;